# GitHub - Personal account (DanielePeruzzi97)
Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_ed25519

# GitHub - Work account (daniele.peruzzi@omnys.com)
Host github-work
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_rsa

# AWS CodeCommit
Host git-codecommit.*.amazonaws.com
  User APKAS52AYCWYFTM444X2
  IdentityFile ~/.ssh/id_rsa
