set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',xterm*:Tc'
set -s escape-time 0
set -s set-clipboard on
set -g mouse on
set -g mode-keys vi
set-option -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1
set-option -g status-position top
set-option -g status-justify absolute-centre
set-option -g detach-on-destroy off

unbind C-b
set -g prefix M-a
bind M-a send-prefix

bind r source-file ~/.tmux.conf \; display-message "Config reloading..."

bind -n M-Left  resize-pane -L 2
bind -n M-Right resize-pane -R 2
bind -n M-Up    resize-pane -U 2
bind -n M-Down  resize-pane -D 2
bind -n M-d kill-pane
bind -n M-H previous-window
bind -n M-L next-window

# vi-style
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

unbind %
unbind '"'
# Split horizontally (v) and vertically (h)
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# Open Lazygit in a new window
bind G neww -n "git" -S lazygit

bind -r T neww -c "#{pane_current_path}" "nvim ~/personal/todo.md"

# Theme options
set -g status-style "bg=default"
set -g status-left "#[bg=default,fg=#ebbcba]#S"
set -g status-right "#[bg=default,fg=#ebbcba]#(date)"
set -g window-status-current-style "fg=#ebbcba"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
